import LoginPage from "@/components/LoginPage";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Login | Election App",
  description: "Generated by create next app",
};

export default function LoginRoute() {
  return (
    <>
      <LoginPage />
    </>
  );
}
