import RegisterPage from "@/components/RegisterPage";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Register | Election App",
  description: "Generated by create next app",
};

export default function RegisterRoute() {
  return (
    <>
      <RegisterPage />
    </>
  );
}
