import { DashboardPage } from "@/components/DashboardPage";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Dashboard | Election App",
  description: "Generated by create next app",
};

export default function DashboardRoute() {
  return <DashboardPage />;
}
